2022-09-08 10:33:34.813572 | Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\Python_Lesson\Lessons\hw_18\employee.py", line 127, in save_email
    self.validate()
  File "C:\Users\admin\PycharmProjects\Python_Lesson\Lessons\hw_18\employee.py", line 116, in validate
    raise EmailAlreadyExistException("This email is already recorded")
employee.EmailAlreadyExistException: This email is already recorded

2022-09-08 10:33:34.842554 | Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\Python_Lesson\Lessons\hw_18\app.py", line 63, in <module>
    main()
  File "C:\Users\admin\PycharmProjects\Python_Lesson\Lessons\hw_18\app.py", line 58, in main
    print(dev2.validate())
  File "C:\Users\admin\PycharmProjects\Python_Lesson\Lessons\hw_18\employee.py", line 116, in validate
    raise EmailAlreadyExistException("This email is already recorded")
employee.EmailAlreadyExistException: This email is already recorded

